apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-55xo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-55xo@sha256:90e24ff0bb8781f061cb8b5d0db09e251ff00a3c8f6ab453748f453e59adefb3
        name: my-nodejs
        resources: {}
status: {}
